#%RAML 1.0 DataType
type: object
properties:
  movieId:
    type: string
    required : true
  movieName:
    type: string
    required: true
  genre:
    type: string
    required: true
  dimension:
    type: string
    required: true
  price:
    type: string
    required: true
  venue:
    type: string
    required: true
  approvedSeats:
    type: string
    required: true
  language:
    type: string
    required: true
  showTiming:
    type: datetime
    required: true  
  description:
    type: string
    required: true  